### ISSUE TITLE
GAMUT_MAX_IMAGE_WIDTH_x_HEIGHT seems to be too restrictive

### ISSUE THREAD

**Issue by gizmomogwai** [AuburnSounds/gamut#47]
I was playing with rather big images, and stumbled over this constant.
I set it now to 0x7fff_ffff / 16 although I am no sure if gamut supports more than 32bit / pixel.
GAMUT_MAX_PIXEL_SIZE seems to indicate that one pixel could even be worth 16 bytes?

**Comment by p0nce** [comment]
- `GAMUT_MAX_PIXEL_SIZE` seems about correct, max pixel size for now is 16-bytes (rgbaf32)

- `GAMUT_MAX_IMAGE_WIDTH_x_HEIGHT` does seem restrictive, it was done because of 32-bit systems, how much would you need that to be? My goal was to make gamut have same limitations in 32-bit and 64-bit, but malloc already doesn't work like that.

**Comment by gizmomogwai** [comment]
- wow ... 4bytes per channel is nice!
- regarding the size i need : ATM i am experimenting with a private project of mine (its an imageviewer that uses a 3d api for rendering the images). so i do not have control on what images i have to represent ... i think the right type to index into a dlang array is size_t (e.g. in `allPixelsAtOnce` there is int used). I would prefer to go with whatever works on the system. If one can allocate enough memory then it should work. I also would not assert on GAMUT_MAX_PIXEL_SIZE but on the real memory used for the image (depending on pixel type and scanline size and so on). and also the asserts are quite evil, the lib should return probably an out_of_memory error image or something like that.

**Comment by p0nce** [comment]
We will disagree a lot. `int` is absolutely the right thing, unsigned integers are evil and people don't have the conversion rules in their head, leading to a lot of bugs in practice.
```d
for (size_t n = 0; n - 1 < LEN; ++n)
{
}
```
It's not a debate I want to have. image.width and height being unsigned would be a bit tragic imo

>  If one can allocate enough memory then it should work.

I'll do like malloc and FreeImage do, not sure what they do for the 32-bit vs 64-bit thing. You are likely right.

**Comment by p0nce** [comment]
More on this https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1428r0.pdf

**Comment by gizmomogwai** [comment]
@p0nce , thanks for the link ... very interesting read, especially since I had exactly subtracted 1 from 0 on an unsigned type yesterday :/. I am also not saying that width and height need to be unsigned, as 31bits are more than enough for me in those two directions :). Still dlang uses size_t to index into an array, so e.g. `allPixelsAtOnce` should use `size_t` as offset into it as well. that being said, again 31bit are also a lot of pixels even in 16byte/pixel :)

**Comment by p0nce** [comment]
How stb does it:

> the various image loaders all have certain limits on image size; these differ somewhat
// by format but generally boil down to either just under 2GB or just under
// 1GB. When the decoded image would be larger than this, stb_image decoding
// will fail.
> // Additionally, stb_image will reject image files that have any of their
// dimensions set to a larger value than the configurable STBI_MAX_DIMENSIONS,
// which defaults to 2**24 = 16777216 pixels. Due to the above memory limit,
// the only way to have an image with such dimensions load correctly
// is for it to have a rather extreme aspect ratio. Either way, the
// assumption here is that such larger images are likely to be malformed
// or malicious. If you do need to load an image with individual dimensions
// larger than that, and it still fits in the overall size limit, you can
// #define STBI_MAX_DIMENSIONS on your own to be something larger.

**Comment by gizmomogwai** [comment]
Thanks a LOT ... just upgraded. I guess the 32bit support is important for auburn sounds, otherwise I would not really support it anymore :)
I wonder if some of those limits are due to limits in the fileformats?

**Comment by p0nce** [comment]
Indeed we continue to have 32-bit customers :) LDC makes it really easy to maintain that compatibility. gamut is also used on arm32 systems by other projects.

Some of the limits are due to the file formats, but not all. Let me know _if_ such a big image ever occur.

**Comment by gizmomogwai** [comment]
I dont think I have enough memory for that ... thanks a lot!
